#i3status-rust
[theme.overrides]
separator       = ""
idle_fg         = "#deddda"
good_fg         = "#deddda"
warning_fg      = "#deddda"
info_fg         = "#deddda"
critical_fg     = "#FF3A3A"

[[block]]
block           = "focused_window"
format          = "$title.str(min_w:220)   |"

[[block]]
block           = "battery"
model           = "SR Real Battery"
format          = "$percentage"
empty_format    = "$percentage"
full_format     = "$percentage"
critical        = 10

[[block]]
block           = "time"
format          = "   $timestamp.datetime(f:'%R   %d/%m')  "
# [[block.click]]
# button = "left"
# cmd = "~/.local/bin/status_calendar.sh"
