filetype plugin indent on
syntax on
autocmd BufReadPost * if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit' | exe "normal! g`\"" | endif

set background=dark

if $TERM != 'linux'
  color default
endif

set nobackup
set noswapfile
set noundofile
set nowrap
set linebreak
set showtabline=2
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set hlsearch
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set viminfo='100,<50,s10,h,n~/.vim/.viminfo
set number
set relativenumber
set laststatus=0
let g:netrw_banner=0
set mouse=a

" FOOT
" Cursor - switch between line and full
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
" Workaround bug in vim, where it incorrectly thinks modifyOtherKeys level 2 is enabled, even when it's not. The snippets below ensure modifyOtherKeys=2 is enabled. 
let &t_TI = "\<Esc>[>4;2m"
let &t_TE = "\<Esc>[>4;m"
set ttimeoutlen=0


nnoremap Q <nop>
nmap <C-S-Right>        :bnext<CR>
nmap <C-S-Left>         :bprevious<CR>
nmap <C-Right>          :tabnext<CR>
nmap <C-Left>           :tabprevious<CR>
"nmap <C-s>              :update<CR>
"imap <C-s>              <Esc>:update<cr>g

" filetype on
let mapleader=' '
nmap <leader>n          :noh<CR>
nmap <leader>ee         :Explore<CR>
nmap <leader>te         :Texplore<CR>
nmap <leader>tt         :tabnew<CR>
nmap <leader><leader>   :ls<CR>:buffer 
nmap <leader>bd         :bwipeout<CR>

