[colors]
background = #000000
background-alt = #2a2a2a
foreground = #d3d3d3
foreground-alt = #ffffff
disable = #808080
; disable = #565656

[bar/example]
override-redirect = true
wm-restack = bspwm
bottom = true
width = 100%
; height = 15pt
height = 16pt
font-0 = FreeSans:bold:size=10;4

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 0
padding-right = 2
module-margin = 1

modules-left = xworkspaces wins
modules-center = xwindow
modules-right = battery date

enable-ipc = false

[module/wins]
type = custom/script
exec = ~/.config/polybar/script/wins2.sh 2> /dev/null
format = <label>
label = %output%
; label = %output:0:15:...%
label-padding = 1
tail = true

[module/xworkspaces]
type = internal/bspwm
enable-scroll = false

label-focused = %index%
label-focused-foreground = ${colors.foreground-alt}
label-focused-background = ${colors.background-alt}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%
label-urgent-padding = 2

label-empty =
; label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:130:...%
format-foreground = ${colors.foreground}

; [module/memory]
; type = internal/memory
; interval = 2
; format-prefix = "RAM "
; format-prefix-foreground = ${colors.primary}
; label = %percentage_used:2%%
; [module/cpu]
; type = internal/cpu
; interval = 2
; format-prefix = "Cpu"
; label = %percentage:2%%

[module/battery]
type = internal/battery
battery = BAT1
adapter = ADP1
poll-interval = 6

[module/date]
type = internal/date
interval = 6
date = %R  %d/%m
; date-alt = %A %d %B
label = %date%
label-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
