# video settings #
autofit-larger=80%x80%
keep-open=yes
# save-position-on-quit=yes
screenshot-directory=~/Imágenes/
screenshot-format=png
blend-subtitles=yes
slang=es
alang=es
osc=no

sub-font='SansSerif'
# sub-bold=yes
# audio settings #
volume=80
ytdl-format='worstvideo+worstaudio/worst'
