hwdec=vaapi
vo=gpu
autofit-larger=80%x80%
keep-open=yes

# save-position-on-quit=yes
sub-auto=all
sub-font='Roboto'
sub-bold=yes
sub-color='#FFFF00'
sub-shadow-color='#000000'
sub-font='Roboto'
sub-bold=no
sub-font-size=32

# osc=no
# script-opts=osc-scalewindowed=0.75, osc-scalefullscreen=0.75
osd-bar=no
osd-on-seek=msg-bar
# osd-font='Roboto'
osd-font='Roboto SemiCondensed'
osd-font-size=28
osd-scale-by-window=no

# script-opts=windowcontrols_title=${volume}

volume=65

screenshot-directory=~/Images/
screenshot-format=png
