autofit-larger=80%x80%
keep-open=yes

# save-position-on-quit=yes
sub-auto=all
sub-font='system-ui'
sub-bold=yes
sub-color='#FFFF00'
sub-shadow-color='#000000'
sub-font='system-ui'
sub-bold=no
sub-font-size=33

osc=no
osd-bar=no
# osd-color='#FFFF00'
osd-on-seek=msg-bar
osd-font='system-ui'
osd-font-size=33
osd-scale-by-window=no

# script-opts=windowcontrols_title=${volume}
# osd-border-size=2
force-window

volume=92

screenshot-directory=~/Imágenes/
screenshot-format=png

# [audio]
# osd-level=3
# geometry=250x228
