set -g default-terminal "$TERM"

set-option -sg escape-time 10                                                                   
# set-option -g focus-events on
set-option -g mouse on
set-option -g set-titles on
# set-option -g set-titles-string "#S#I #W"
set-option -g set-titles-string "#W - #T"

unbind-key C-z
unbind-key C-b

set-option -g prefix C-a
bind-key C-a send-prefix

set -g status off
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

bind-key j join-pane -h -s !
bind-key J join-pane -v -s !

# Switch panes 
# Usage: "Alt+" (without prefix key)
bind -n M-Left      select-pane -L
bind -n M-Right     select-pane -R
bind -n M-Up        select-pane -U
bind -n M-Down      select-pane -D
bind -n M-PageUp    previous-window
bind -n M-PageDown  next-window
# select-pane -t :.+
# resize-pane -L 5
# resize-pane -R 5
# resize-pane -U 5
# resize-pane -D 5
# set-window-option -g mode-keys vi
# bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T copy-mode-vi y send-keys -X copy-selection

bind -n C-b set -g status

bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window      -c "#{pane_current_path}"
bind-key s choose-tree -ZsN
bind-key w choose-tree -ZN

# THEME
set -g pane-active-border-style bg=default,fg=black
set -g pane-border-style bg=default,fg=black

set -g status-right ""
set -g status-style bg=black,fg=grey
set -g window-status-current-style bg=black,fg=white,bold

set -g message-style bg=black,fg=white
set -g mode-style bg=grey,fg=black
set -g clock-mode-colour grey
