# set -g default-terminal xterm-256color
set -g default-terminal "$TERM"
# set -g extended-keys always
# bind-key -n Home send Escape "OH"
# bind-key -n End send Escape "OF"

set-option -sg escape-time 10                                                                   
set-option -g focus-events on
set-option -g mouse on

unbind-key C-z
unbind-key C-b

set-option -g prefix C-a
bind-key C-a send-prefix

# set -g status off
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

bind-key j join-pane -h -s !
bind-key J join-pane -v -s !

# Switch panes 
# Usage: "SHIFT+" (without prefix key)
# bind -n S-Left select-pane -L
# bind -n S-Right select-pane -R
# bind -n S-Up select-pane -U
# bind -n S-Down select-pane -D
# Switch windows 
# Usage: "SHIFT+" (without prefix key)
bind -n S-Left previous-window
bind -n S-Right next-window

# THEME
set -g pane-active-border-style bg=default,fg=black
set -g pane-border-style bg=default,fg=black

set -g status-right ""
set -g status-style bg=black,fg=grey
set -g window-status-current-style bg=black,fg=white,bold

set -g message-style bg=black,fg=grey,bold
set -g mode-style bg=grey,fg=black
set -g clock-mode-colour grey
