# -*- conf -*-
# vim: filetype=yaml :
# vim: syntax=yaml :

term=xterm-256color
font=monospace:size=11
line-height=18px
font-size-adjustment=1
pad=14x8
initial-window-size-pixels=1162x1062

[main]
include=/usr/share/foot/themes/kitty

[scrollback]
indicator-position=none
indicator-format=none

[url]
launch=chromium ${url}

[cursor]
color=1a1a1a 9fd5f5

[key-bindings]
scrollback-up-page=Shift+KP_Prior
scrollback-down-page=Shift+KP_Next
spawn-terminal=Control+Shift+Return
