# -*- conf -*-
# vim: filetype=sh :
# vim: syntax=sh :

term=xterm-256color
# app-id=foot
font=monospace:size=11
font-size-adjustment=1
initial-window-size-pixels=1918x1059
# initial-window-size-chars=211x57
# initial-window-mode=windowed
pad=7x7
[scrollback]
indicator-position=none
indicator-format=none

[mouse]
hide-when-typing=no
# alternate-scroll-mode=yes

[colors]
# alpha=0.94
background=000000
foreground=f6f5f4
# flash=7f7f00
# flash-alpha=0.5

regular0=000000 # black
regular1=cd3131 # red
regular2=0dbc79 # green
regular3=e5e510 # yellow
regular4=2472c8 # blue
regular5=bc3fbc # magenta
regular6=11a8cd # cyan
regular7=e5e5e5 # white

bright0=666666 # bright black
bright1=f14c4c # bright red
bright2=23d18b # bright green
bright3=f5f543 # bright yellow
bright4=3b8eea # bright blue
bright5=d670d6 # bright magenta
bright6=29b8db # bright cyan
bright7=e5e5e5 # bright white
