# -*- conf -*-
# vim: filetype=yaml :
# vim: syntax=yaml :

term=xterm-256color
font=monospace:size=11
line-height=18px
font-size-adjustment=1
initial-window-size-pixels=1170x1078
# initial-window-size-pixels=1170x1040
pad=14x8
# pad=5x8

[main]
include=/usr/share/foot/themes/kitty

[scrollback]
indicator-position=none
indicator-format=none
# multiplier=3.5

[url]
launch=chromium ${url}

[mouse]
hide-when-typing=no
# alternate-scroll-mode=yes
[cursor]
color=1a1a1a 9fd5f5
