# https://github.com/9ary/gebaar-libinput-fork
# [swipe.commands.three]
# up = "rofi -show window"
# down = "bspc node -f last.window.local || bspc node -f next.window.local"
# left = "bspc desktop -f next.occupied.local"
# right = "bspc desktop -f prev.occupied.local"
# [swipe.commands.four]
# up = "rofi -show drun"
# down = "rofi -show drun"
# right = "bspc node -d prev.local --follow"
# left = "bspc node -d next.local --follow"
# HYPRLAND :c
[swipe.commands.three]
# up = '~/.config/hypr/scripts/bemenu_window.sh'
down = '~/.config/hypr/scripts/hypr_lastwindow.sh'
right = 'hyprctl dispatch workspace e-1 > /dev/null 2>&1'
left = 'hyprctl dispatch workspace e+1 > /dev/null 2>&1'
