# https://github.com/9ary/gebaar-libinput-fork
[swipe.commands.three]
up = "rofi -show window"
down = "bspc node -f last.window.local || bspc node -f next.window.local"
right = "bspc desktop -f prev.occupied.local"
left = "bspc desktop -f next.occupied.local"

[swipe.commands.four]
up = "rofi -show drun"
down = "rofi -show drun"
right = "bspc node -d prev.local --follow"
left = "bspc node -d next.local --follow"
