# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

general {
    no_fade_in = true
    no_fade_out	= true
    disable_loading_bar = true
    ignore_empty_input = true
}
background {
    color = rgb(000000)
}
input-field {
    monitor =
    size = 300,40
    outline_thickness = 0
    rounding = 0
    dots_size = 0.25
    dots_fade_time = 0
    dots_text_format = ⋆
    font_family = FreeSans Bold
    fade_on_empty = false
    placeholder_text = <span>password</span>
    fail_text = <span>password</span>
    inner_color = rgb(000000)
    font_color = rgb(deddda)
    swap_font_color = true
}
label {
    monitor =
    text = <span>lock</span>
    color = rgb(deddda)
    font_family = FreeSans Bold
    font_size = 10
    position = 6,1
    halign = left
    valign = bottom
}
